import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:file_saver/file_saver.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../../../core/theme/app_theme.dart';

class InteractiveQuizWidget extends StatefulWidget {
  final Map<String, dynamic> quizData;

  const InteractiveQuizWidget({super.key, required this.quizData});

  @override
  State<InteractiveQuizWidget> createState() => _InteractiveQuizWidgetState();
}

class _InteractiveQuizWidgetState extends State<InteractiveQuizWidget> with SingleTickerProviderStateMixin {
  late List<dynamic> questions;
  Map<int, int> selectedAnswers = {};
  bool isSubmitted = false;
  int score = 0;
  Uint8List? _questionPaperBytes;
  late TabController _tabController;

  int _getAnswerIndex(dynamic q) {
    final map = q as Map;
    return (map['answerIndex'] ?? map['correctIndex'] ?? 0) as int;
  }

  @override
  void initState() {
    super.initState();
    questions = widget.quizData['questions'] ?? [];
    _tabController = TabController(length: 2, vsync: this);
    _generatePdf();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _submitQuiz() {
    int calculatedScore = 0;
    for (int i = 0; i < questions.length; i++) {
      if (selectedAnswers[i] == _getAnswerIndex(questions[i])) {
        calculatedScore++;
      }
    }
    setState(() {
      score = calculatedScore;
      isSubmitted = true;
    });
  }

  pw.Document _buildPdf() {
    final pdf = pw.Document();
    final title = widget.quizData['title'] ?? 'Question Paper';
    final subject = widget.quizData['subject']?.toString();
    final duration = widget.quizData['durationMinutes']?.toString();
    final instructions = widget.quizData['instructions']?.toString();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          final List<pw.Widget> widgets = [];

          widgets.add(
            pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
          );
          widgets.add(pw.Text('Generated by Kimi K3', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)));
          if (subject != null && subject.isNotEmpty) {
            widgets.add(pw.SizedBox(height: 4));
            widgets.add(pw.Text('Subject: $subject', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)));
          }
          if (duration != null && duration.isNotEmpty) {
            widgets.add(pw.Text('Duration: $duration minutes', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)));
          }
          widgets.add(pw.SizedBox(height: 8));
          if (instructions != null && instructions.isNotEmpty) {
            widgets.add(pw.Container(
              padding: const pw.EdgeInsets.all(12),
              color: PdfColors.grey100,
              child: pw.Text(instructions, style: const pw.TextStyle(fontSize: 12, fontStyle: pw.FontStyle.italic)),
            ));
            widgets.add(pw.SizedBox(height: 16));
          }
          widgets.add(pw.SizedBox(height: 12));

          for (int i = 0; i < questions.length; i++) {
            final q = questions[i];
            widgets.add(
              pw.Text('Q${i + 1}. ${q['question']}', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            );
            widgets.add(pw.SizedBox(height: 8));

            final options = q['options'] as List;
            for (int j = 0; j < options.length; j++) {
              widgets.add(
                pw.Padding(
                  padding: const pw.EdgeInsets.only(left: 16, bottom: 4),
                  child: pw.Text('[${String.fromCharCode(65 + j)}] ${options[j]}', style: const pw.TextStyle(fontSize: 12)),
                ),
              );
            }
            widgets.add(pw.SizedBox(height: 16));
          }

          return widgets;
        },
      ),
    );
    return pdf;
  }

  Future<void> _generatePdf() async {
    try {
      final pdf = _buildPdf();
      final bytes = await pdf.save();
      if (mounted) {
        setState(() => _questionPaperBytes = bytes);
      }
    } catch (_) {}
  }

  Future<void> _downloadQuestionPaper() async {
    try {
      final pdf = _buildPdf();
      final bytes = await pdf.save();
      await FileSaver.instance.saveFile(
        name: 'QuestionPaper',
        bytes: bytes,
        fileExtension: 'pdf',
        mimeType: MimeType.pdf,
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Question Paper downloaded as PDF!')));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Failed to download: $e')));
      }
    }
  }

  Future<void> _downloadAnswerScript() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          final List<pw.Widget> widgets = [];

          widgets.add(
            pw.Text('Answer Script', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
          );
          widgets.add(pw.Text('Generated by Kimi K3', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)));
          widgets.add(pw.SizedBox(height: 20));

          for (int i = 0; i < questions.length; i++) {
            final q = questions[i];
            widgets.add(
              pw.Text('Q${i + 1}. ${q['question']}', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            );
            widgets.add(pw.SizedBox(height: 4));

            final answerIndex = _getAnswerIndex(q);
            final options = q['options'] as List;
            final answerText = answerIndex < options.length ? options[answerIndex] : 'N/A';

            widgets.add(
              pw.Text('Answer: [${String.fromCharCode(65 + answerIndex)}] $answerText', style: pw.TextStyle(fontSize: 14, color: PdfColors.green700)),
            );
            widgets.add(pw.SizedBox(height: 16));
          }

          return widgets;
        },
      ),
    );

    try {
      final bytes = await pdf.save();
      await FileSaver.instance.saveFile(
        name: 'AnswerScript',
        bytes: bytes,
        fileExtension: 'pdf',
        mimeType: MimeType.pdf,
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Answer Script downloaded as PDF!')));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Failed to download: $e')));
      }
    }
  }

  Widget _buildQuizTab() {
    if (questions.isEmpty) {
      return Center(child: Text('No questions available.'));
    }
    return ListView.builder(
      padding: EdgeInsets.only(top: 8, bottom: 8),
      itemCount: questions.length,
      itemBuilder: (context, index) {
        final q = questions[index];
        final options = (q['options'] as List?) ?? [];
        final correctIdx = _getAnswerIndex(q);
        return Padding(
          padding: EdgeInsets.only(bottom: 24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Q${index + 1}. ${q['question']}', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
              SizedBox(height: 12),
              ...List.generate(options.length, (optIndex) {
                final optionText = options[optIndex].toString();
                bool isSelected = selectedAnswers[index] == optIndex;
                bool isCorrect = correctIdx == optIndex;

                Color bgColor = Colors.transparent;
                Color borderColor = Colors.grey.shade300;

                if (isSubmitted) {
                  if (isCorrect) {
                    bgColor = Colors.green.withAlpha(30);
                    borderColor = Colors.green;
                  } else if (isSelected && !isCorrect) {
                    bgColor = Colors.red.withAlpha(30);
                    borderColor = Colors.red;
                  }
                } else if (isSelected) {
                  bgColor = AppTheme.primary.withAlpha(20);
                  borderColor = AppTheme.primary;
                }

                return InkWell(
                  onTap: isSubmitted ? null : () {
                    setState(() {
                      selectedAnswers[index] = optIndex;
                    });
                  },
                  child: Container(
                    width: double.infinity,
                    margin: EdgeInsets.only(bottom: 8),
                    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                    decoration: BoxDecoration(
                      color: bgColor,
                      border: Border.all(color: borderColor),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      children: [
                        Text('${String.fromCharCode(65 + optIndex)}.', style: TextStyle(fontWeight: FontWeight.bold)),
                        SizedBox(width: 8),
                        Expanded(child: Text(optionText)),
                        if (isSubmitted && isCorrect) Icon(Icons.check_circle, color: Colors.green, size: 20),
                        if (isSubmitted && isSelected && !isCorrect) Icon(Icons.cancel, color: Colors.red, size: 20),
                      ],
                    ),
                  ),
                );
              }),
            ],
          ),
        );
      },
    );
  }

  Widget _buildPdfPreviewTab() {
    if (_questionPaperBytes == null) {
      return Center(child: CircularProgressIndicator());
    }
    return PdfPreview(
      build: (_) => Uint8List.fromList(_questionPaperBytes!),
      canChangePageFormat: false,
      canChangeOrientation: false,
      canDebug: false,
      allowPrinting: true,
      allowSharing: true,
      pdfFileName: '${widget.quizData['title'] ?? 'QuestionPaper'}.pdf',
    );
  }

  @override
  Widget build(BuildContext context) {
    if (questions.isEmpty) {
      return Text('Invalid quiz data.');
    }
    final title = widget.quizData['title'] ?? 'Interactive Quiz';

    return Container(
      margin: EdgeInsets.symmetric(vertical: 8),
      padding: EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: AppTheme.primary.withAlpha(50)),
        borderRadius: BorderRadius.circular(12),
        boxShadow: const [BoxShadow(color: Color(0x0A000000), blurRadius: 8, offset: Offset(0, 2))],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          Row(
            children: [
              Icon(Icons.quiz, color: AppTheme.primary),
              SizedBox(width: 8),
              Expanded(
                child: Text(title, style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppTheme.primary)),
              ),
            ],
          ),
          SizedBox(height: 12),
          TabBar(
            controller: _tabController,
            labelColor: AppTheme.primary,
            unselectedLabelColor: Colors.grey,
            indicatorColor: AppTheme.primary,
            tabs: const [
              Tab(text: 'Quiz'),
              Tab(text: 'PDF Preview'),
            ],
          ),
          SizedBox(
            height: 400,
            child: TabBarView(
              controller: _tabController,
              children: [
                _buildQuizTab(),
                _buildPdfPreviewTab(),
              ],
            ),
          ),
          if (!isSubmitted)
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                style: ElevatedButton.styleFrom(backgroundColor: AppTheme.primary, foregroundColor: Colors.white),
                onPressed: selectedAnswers.length == questions.length ? _submitQuiz : null,
                child: Text('Submit Answers'),
              ),
            ),
          if (isSubmitted) ...[
            const Divider(),
            Center(
              child: Text(
                'Score: $score / ${questions.length}',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: AppTheme.primary),
              ),
            ),
            SizedBox(height: 16),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                OutlinedButton.icon(
                  onPressed: _downloadQuestionPaper,
                  icon: Icon(Icons.download),
                  label: Text('Question Paper', style: TextStyle(fontSize: 12)),
                ),
                OutlinedButton.icon(
                  onPressed: _downloadAnswerScript,
                  icon: Icon(Icons.file_download_done),
                  label: Text('Answer Script', style: TextStyle(fontSize: 12)),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }
}
