import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:file_saver/file_saver.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../../../core/theme/app_theme.dart';

class InteractiveQuizWidget extends StatefulWidget {
  final Map<String, dynamic> quizData;

  const InteractiveQuizWidget({super.key, required this.quizData});

  @override
  State<InteractiveQuizWidget> createState() => _InteractiveQuizWidgetState();
}

class _InteractiveQuizWidgetState extends State<InteractiveQuizWidget> {
  late List<dynamic> questions;
  Map<int, int> selectedAnswers = {};
  bool isSubmitted = false;
  int score = 0;

  @override
  void initState() {
    super.initState();
    questions = widget.quizData['questions'] ?? [];
  }

  void _submitQuiz() {
    int calculatedScore = 0;
    for (int i = 0; i < questions.length; i++) {
      if (selectedAnswers[i] == questions[i]['answerIndex']) {
        calculatedScore++;
      }
    }
    setState(() {
      score = calculatedScore;
      isSubmitted = true;
    });
  }

  Future<void> _downloadQuestionPaper() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          final List<pw.Widget> widgets = [];
          
          widgets.add(
            pw.Header(
              level: 0,
              child: pw.Text('Question Paper', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
            )
          );
          widgets.add(pw.Text('Generated by Kimi K3', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)));
          widgets.add(pw.SizedBox(height: 20));

          for (int i = 0; i < questions.length; i++) {
            final q = questions[i];
            widgets.add(
              pw.Text('Q${i + 1}. ${q['question']}', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold))
            );
            widgets.add(pw.SizedBox(height: 8));
            
            final options = q['options'] as List;
            for (int j = 0; j < options.length; j++) {
              widgets.add(
                pw.Padding(
                  padding: const pw.EdgeInsets.only(left: 16, bottom: 4),
                  child: pw.Text('[${String.fromCharCode(65 + j)}] ${options[j]}', style: const pw.TextStyle(fontSize: 12))
                )
              );
            }
            widgets.add(pw.SizedBox(height: 16));
          }
          
          return widgets;
        },
      ),
    );

    try {
      final bytes = await pdf.save();
      await FileSaver.instance.saveFile(
        name: 'QuestionPaper',
        bytes: bytes,
        fileExtension: 'pdf',
        mimeType: MimeType.pdf,
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Question Paper downloaded as PDF!')));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Failed to download: $e')));
      }
    }
  }

  Future<void> _downloadAnswerScript() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          final List<pw.Widget> widgets = [];
          
          widgets.add(
            pw.Header(
              level: 0,
              child: pw.Text('Answer Script', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
            )
          );
          widgets.add(pw.Text('Generated by Kimi K3', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)));
          widgets.add(pw.SizedBox(height: 20));

          for (int i = 0; i < questions.length; i++) {
            final q = questions[i];
            widgets.add(
              pw.Text('Q${i + 1}. ${q['question']}', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold))
            );
            widgets.add(pw.SizedBox(height: 4));
            
            final answerIndex = q['answerIndex'] as int;
            final answerText = q['options'][answerIndex];
            
            widgets.add(
              pw.Text('Answer: [${String.fromCharCode(65 + answerIndex)}] $answerText', style: pw.TextStyle(fontSize: 14, color: PdfColors.green700))
            );
            widgets.add(pw.SizedBox(height: 16));
          }
          
          return widgets;
        },
      ),
    );

    try {
      final bytes = await pdf.save();
      await FileSaver.instance.saveFile(
        name: 'AnswerScript',
        bytes: bytes,
        fileExtension: 'pdf',
        mimeType: MimeType.pdf,
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Answer Script downloaded as PDF!')));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Failed to download: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    if (questions.isEmpty) {
      return const Text('Invalid quiz data.');
    }

    return Container(
      margin: const EdgeInsets.symmetric(vertical: 8),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: AppTheme.primary.withAlpha(50)),
        borderRadius: BorderRadius.circular(12),
        boxShadow: const [BoxShadow(color: Color(0x0A000000), blurRadius: 8, offset: Offset(0, 2))],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.quiz, color: AppTheme.primary),
              const SizedBox(width: 8),
              Expanded(
                child: Text(widget.quizData['title'] ?? 'Interactive Quiz', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppTheme.primary)),
              ),
            ],
          ),
          const SizedBox(height: 16),
          ...List.generate(questions.length, (index) {
            final q = questions[index];
            return Padding(
              padding: const EdgeInsets.only(bottom: 24.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Q${index + 1}. ${q['question']}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                  const SizedBox(height: 12),
                  ...List.generate((q['options'] as List).length, (optIndex) {
                    final optionText = q['options'][optIndex];
                    bool isSelected = selectedAnswers[index] == optIndex;
                    bool isCorrect = q['answerIndex'] == optIndex;
                    
                    Color bgColor = Colors.transparent;
                    Color borderColor = Colors.grey.shade300;
                    
                    if (isSubmitted) {
                      if (isCorrect) {
                        bgColor = Colors.green.withAlpha(30);
                        borderColor = Colors.green;
                      } else if (isSelected && !isCorrect) {
                        bgColor = Colors.red.withAlpha(30);
                        borderColor = Colors.red;
                      }
                    } else if (isSelected) {
                      bgColor = AppTheme.primary.withAlpha(20);
                      borderColor = AppTheme.primary;
                    }

                    return InkWell(
                      onTap: isSubmitted ? null : () {
                        setState(() {
                          selectedAnswers[index] = optIndex;
                        });
                      },
                      child: Container(
                        width: double.infinity,
                        margin: const EdgeInsets.only(bottom: 8),
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                        decoration: BoxDecoration(
                          color: bgColor,
                          border: Border.all(color: borderColor),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Row(
                          children: [
                            Text('${String.fromCharCode(65 + optIndex)}.', style: const TextStyle(fontWeight: FontWeight.bold)),
                            const SizedBox(width: 8),
                            Expanded(child: Text(optionText)),
                            if (isSubmitted && isCorrect) const Icon(Icons.check_circle, color: Colors.green, size: 20),
                            if (isSubmitted && isSelected && !isCorrect) const Icon(Icons.cancel, color: Colors.red, size: 20),
                          ],
                        ),
                      ),
                    );
                  }),
                ],
              ),
            );
          }),
          if (!isSubmitted)
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                style: ElevatedButton.styleFrom(backgroundColor: AppTheme.primary, foregroundColor: Colors.white),
                onPressed: selectedAnswers.length == questions.length ? _submitQuiz : null,
                child: const Text('Submit Answers'),
              ),
            ),
          if (isSubmitted) ...[
            const Divider(),
            Center(
              child: Text(
                'Score: $score / ${questions.length}',
                style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: AppTheme.primary),
              ),
            ),
            const SizedBox(height: 16),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                OutlinedButton.icon(
                  onPressed: _downloadQuestionPaper,
                  icon: const Icon(Icons.download),
                  label: const Text('Question Paper', style: TextStyle(fontSize: 12)),
                ),
                OutlinedButton.icon(
                  onPressed: _downloadAnswerScript,
                  icon: const Icon(Icons.file_download_done),
                  label: const Text('Answer Script', style: TextStyle(fontSize: 12)),
                ),
              ],
            )
          ]
        ],
      ),
    );
  }
}
